{{- if eq .Values.config.storage.engine "blocks" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex.storeGatewayFullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cortex.storeGatewayLabels" . | nindent 4 }}
    {{- with .Values.store_gateway.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.store_gateway.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.config.server.grpc_listen_port }}
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector:
    {{- include "cortex.storeGatewaySelectorLabels" . | nindent 4 }}
{{- end -}}
