{{- if .Values.ruler.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex.rulerFullname" . }}
  labels:
    {{- include "cortex.rulerLabels" . | nindent 4 }}
    {{- with .Values.ruler.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.ruler.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    {{- include "cortex.rulerSelectorLabels" . | nindent 4 }}
{{- end }}
