loki:
  config: |
    server:
      http_listen_port: 3100
    distributor:
      ring:
        kvstore:
          store: memberlist
    memberlist:
      join_members:
        - {{ include "loki.fullname" . }}-memberlist
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      chunk_idle_period: 30m
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_retain_period: 1m
      max_transfer_retries: 0
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
    schema_config:
      configs:
        - chunks:
            period: 360h
            prefix: loki_chunk_
          from: "2021-02-01"
          index:
            period: 360h
            prefix: loki_index_
          object_store: cassandra
          schema: v11
          store: cassandra
    storage_config:
      cassandra:
        addresses: cassandra.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}
        auth: true
        username: cassandra
        password: cassandra
        keyspace: loki
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      creation_grace_period: 3h
      poll_interval: 10m
      retention_deletes_enabled: false
      retention_period: 0s
    query_range:
      align_queries_with_step: true
      max_retries: 5
      split_queries_by_interval: 15m
      cache_results: true
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_items: 1024
            validity: 24h
    frontend_worker:
      frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095
    frontend:
      log_queries_longer_than: 5s
      compress_responses: true
    compactor:
      shared_store: filesystem
    ruler:
      storage:
        type: local
        local:
          directory: /etc/loki/rules
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      alertmanager_url: https://alertmanager.xx
      external_url: https://alertmanager.xx

tableManager:
  enabled: true

memcachedExporter:
  enabled: true

memcachedChunks:
  enabled: true

memcachedFrontend:
  enabled: true

memcachedIndexQueries:
  enabled: true

memcachedIndexWrites:
  enabled: true
