service:
  type: ClusterIP

admin:
  userKey: admin-user
  passwordKey: admin-password

persistence:
  type: pvc
  enabled: true
  storageClassName: "kubermatic-fast"

grafana.ini:
  auth.proxy:
    enabled: true
    header_name: "X-Forwarded-Email"
    header_property: "username"
    auto_sign_up: "true"
