service:
  type: ClusterIP

replicas: 2

admin:
  userKey: admin-user
  passwordKey: admin-password

persistence:
  type: statefulset
  enabled: true
  storageClassName: "kubermatic-fast"

grafana.ini:
  auth.proxy:
    enabled: true
    header_name: "X-Forwarded-Email"
    header_property: "username"
    auto_sign_up: "true"

  ## Enable alerting features
  plugins:
    enable_alpha: true
  feature_toggles:
    enable: ngalert
