service:
  type: LoadBalancer

admin:
  userKey: admin-user
  passwordKey: admin-password
# adminUser: admin
# adminPassword: admin

persistence:
  type: pvc
  enabled: true
  # storageClassName: "kubermatic-fast"

grafana.ini:
  auth.proxy:
    enabled: true
    header_name: "X-WEBAUTH-USER"
    header_property: "username"
    auto_sign_up: "true"

