{{- if and (gt (int .Values.alertmanager.replicas) 1) (.Values.alertmanager.podDisruptionBudget) }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cortex.alertmanagerFullname" . }}
  labels:
    {{- include "cortex.alertmanagerLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cortex.alertmanagerSelectorLabels" . | nindent 6 }}
  {{- toYaml .Values.alertmanager.podDisruptionBudget | nindent 2 }}
{{- end }}
