apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex.querierFullname" . }}
  labels:
    {{- include "cortex.querierLabels" . | nindent 4 }}
    {{- with .Values.querier.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.querier.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    {{- include "cortex.querierSelectorLabels" . | nindent 4 }}
