apiVersion: v1
kind: Service
metadata:
  name: prom-label-proxy
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: mla
    app.kubernetes.io/component: prom-label-proxy

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-label-proxy
  labels:
    app.kubernetes.io/name: mla
    app.kubernetes.io/component: prom-label-proxy
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: mla
      app.kubernetes.io/component: prom-label-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mla
        app.kubernetes.io/component: prom-label-proxy
    spec:
      securityContext:
        fsGroup: 101
        runAsGroup: 101
        runAsNonRoot: true
        runAsUser: 101
      terminationGracePeriodSeconds: 30
      containers:
        - name: prom-label-proxy
          args:
            - -enable-label-apis
            - -label=tenant_id
            - -upstream=http://thanos-query-frontend.{{ .Values.mla.namespace }}.svc.cluster.local:9090
            - -insecure-listen-address=0.0.0.0:8080
          image: quay.io/prometheuscommunity/prom-label-proxy:master
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          resources:
            {}
