apiVersion: v1
kind: Secret
metadata:
  name: grafana
type: Opaque
data:
  admin-user: {{ .Values.grafana.adminUser | b64enc | quote }}
  {{- if .Values.grafana.adminPassword }}
  admin-password: {{ .Values.grafana.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
  {{- if and .Values.grafana.ldap.enabled .Values.grafana.ldap.config }}
  ldap-toml: {{ tpl .Values.grafana.ldap.config $ | b64enc | quote }}
  {{- end }}
