apiVersion: v1
kind: Secret
metadata:
  name: minio
type: Opaque
data:
  accesskey: {{ if .Values.minio.accessKey }}{{ .Values.minio.accessKey | toString | b64enc | quote }}{{ else }}{{ randAlphaNum 20 | b64enc | quote }}{{ end }}
  secretkey: {{ if .Values.minio.secretKey }}{{ .Values.minio.secretKey | toString | b64enc | quote }}{{ else }}{{ randAlphaNum 40 | b64enc | quote }}{{ end }}
{{- if and .Values.minio.gcsgateway.enabled .Values.minio.gcsgateway.gcsKeyJson }}
  gcs_key.json: {{ .Values.minio.gcsgateway.gcsKeyJson | toString | b64enc }}
{{- end }}
{{- if .Values.minio.s3gateway.enabled -}}
{{- if .Values.minio.s3gateway.accessKey }}
  awsAccessKeyId: {{ .Values.minio.s3gateway.accessKey | toString | b64enc | quote }}
{{- end }}
{{- if .Values.minio.s3gateway.secretKey }}
  awsSecretAccessKey: {{ .Values.minio.s3gateway.secretKey | toString | b64enc | quote }}
{{- end }}
{{- end }}
{{- if .Values.minio.etcd.clientCert }}
  etcd_client_cert.pem: {{ .Values.minio.etcd.clientCert | toString | b64enc | quote }}
{{- end }}
{{- if .Values.minio.etcd.clientCertKey }}
  etcd_client_cert_key.pem: {{ .Values.minio.etcd.clientCertKey | toString | b64enc | quote }}
{{- end }}
