apiVersion: v2
version: 0.7.0
appVersion: v1.10.0
description: 'Horizontally scalable, highly available, multi-tenant, long term Prometheus.'
home: https://cortexmetrics.io/
kubeVersion: ^1.19.0-0
name: cortex
sources:
  - https://github.com/cortexproject/cortex-helm-chart
dependencies:
  - name: cortex
    repository: https://cortexproject.github.io/cortex-helm-chart
    version: 0.7.0
