{
 "title": "Nodes Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "nodes",
    "label": "Nodes",
    "query": {
     "query": "label_values(node_boot_time_seconds{job=\"node-exporter\"}, node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (node_name) (sum by (node_name) (irate(node_cpu_seconds_total{jobLabel=\"node-exporter\", mode!=\"idle\", node_name=~\"$nodes\"}[2m]) * 100))",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (sum by (node_name) (irate(node_cpu_seconds_total{jobLabel=\"node-exporter\", mode!=\"idle\", node_name=~\"$nodes\"}[2m]) * 100))"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (node_name) (\n  node_memory_MemTotal_bytes{jobLabel=\"node-exporter\", node_name=~\"$nodes\"}\n  - node_memory_MemFree_bytes{jobLabel=\"node-exporter\", node_name=~\"$nodes\"}\n  - node_memory_Buffers_bytes{jobLabel=\"node-exporter\", node_name=~\"$nodes\"}\n  - node_memory_Cached_bytes{jobLabel=\"node-exporter\", node_name=~\"$nodes\"}\n)\n",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  (\n    sum(\n      node_memory_MemTotal_bytes{jobLabel=\"node-exporter\", node_name=~\"$nodes\"}\n    - node_memory_MemFree_bytes{jobLabel=\"node-exporter\", node_name=~\"$nodes\"}\n    - node_memory_Buffers_bytes{jobLabel=\"node-exporter\", node_name=~\"$nodes\"}\n    - node_memory_Cached_bytes{jobLabel=\"node-exporter\", node_name=~\"$nodes\"}\n    )\n    /\n    sum(\n      node_memory_MemTotal_bytes{jobLabel=\"node-exporter\", node_name=~\"$nodes\"}\n    )\n  ) * 100)"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (node_name) (rate(node_network_receive_bytes_total{jobLabel=\"node-exporter\", node_name=~\"$nodes\"}[2m]))",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Network Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (node_name) (rate(node_network_transmit_bytes_total{jobLabel=\"node-exporter\", node_name=~\"$nodes\"}[2m]))",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (node_name) (rate(node_disk_read_bytes_total{jobLabel=\"node-exporter\", node_name=~\"$nodes\"}[2m]))",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Disk Written",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (node_name) (rate(node_disk_written_bytes_total{jobLabel=\"node-exporter\", node_name=~\"$nodes\"}[2m]))",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Disk I/O Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (node_name) (rate(node_disk_io_time_seconds_total{jobLabel=\"node-exporter\", node_name=~\"$nodes\"}[2m]))",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - sum by (node_name) (node_filesystem_avail_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", node_name=~\"$nodes\"}) / sum by (node_name) (node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", node_name=~\"$nodes\"})",
     "legendFormat": "{{ node_name }}"
    }
   ]
  }
 ]
}
{
 "title": "Nodes",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_boot_time_seconds, node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(node_load1{jobLabel=\"node-exporter\", node_name=\"$node\"})",
     "legendFormat": "load 1m"
    },
    {
     "expr": "max(node_load5{jobLabel=\"node-exporter\", node_name=\"$node\"})",
     "legendFormat": "load 5m"
    },
    {
     "expr": "max(node_load15{jobLabel=\"node-exporter\", node_name=\"$node\"})",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "CPU Utilization per Core",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (cpu) (irate(node_cpu_seconds_total{jobLabel=\"node-exporter\", mode!=\"idle\", node_name=\"$node\"}[5m]) * 100)",
     "legendFormat": "core {{ cpu }}"
    }
   ]
  },
  {
   "title": "Average CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(sum by (cpu) (irate(node_cpu_seconds_total{jobLabel=\"node-exporter\", mode!=\"idle\", node_name=\"$node\"}[2m]) * 100))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (sum by (cpu) (irate(node_cpu_seconds_total{jobLabel=\"node-exporter\", mode!=\"idle\", node_name=\"$node\"}[2m]) * 100))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(\n  node_memory_MemTotal_bytes{jobLabel=\"node-exporter\", node_name=\"$node\"}\n  - node_memory_MemFree_bytes{jobLabel=\"node-exporter\", node_name=\"$node\"}\n  - node_memory_Buffers_bytes{jobLabel=\"node-exporter\", node_name=\"$node\"}\n  - node_memory_Cached_bytes{jobLabel=\"node-exporter\", node_name=\"$node\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "max(node_memory_Buffers_bytes{jobLabel=\"node-exporter\", node_name=\"$node\"})",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "max(node_memory_Cached_bytes{jobLabel=\"node-exporter\", node_name=\"$node\"})",
     "legendFormat": "memory cached"
    },
    {
     "expr": "max(node_memory_MemFree_bytes{jobLabel=\"node-exporter\", node_name=\"$node\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Current Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  (\n    (\n      node_memory_MemTotal_bytes{jobLabel=\"node-exporter\", node_name=\"$node\"}\n    - node_memory_MemFree_bytes{jobLabel=\"node-exporter\", node_name=\"$node\"}\n    - node_memory_Buffers_bytes{jobLabel=\"node-exporter\", node_name=\"$node\"}\n    - node_memory_Cached_bytes{jobLabel=\"node-exporter\", node_name=\"$node\"}\n    )\n    / node_memory_MemTotal_bytes{jobLabel=\"node-exporter\", node_name=\"$node\"}\n  ) * 100)"
    }
   ]
  },
  {
   "title": "Inode Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(\n  node_filesystem_files{jobLabel=\"node-exporter\", node_name=\"$node\"}\n  - node_filesystem_files_free{jobLabel=\"node-exporter\", node_name=\"$node\"}\n)",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Current Inode Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  (\n    (\n      node_filesystem_files{jobLabel=\"node-exporter\", node_name=\"$node\"}\n    - node_filesystem_files_free{jobLabel=\"node-exporter\", node_name=\"$node\"}\n    )\n    / node_filesystem_files{jobLabel=\"node-exporter\", node_name=\"$node\"}\n  ) * 100)"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_disk_read_bytes_total{jobLabel=\"node-exporter\", node_name=\"$node\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{jobLabel=\"node-exporter\", node_name=\"$node\"}[2m]))",
     "legendFormat": "written"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_network_receive_bytes_total{jobLabel=\"node-exporter\", node_name=\"$node\", device!~\"lo\"}[2m]))",
     "legendFormat": "received"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{jobLabel=\"node-exporter\", node_name=\"$node\", device!~\"lo\"}[2m]))",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Disk I/O Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_disk_io_time_seconds_total{jobLabel=\"node-exporter\",  node_name=\"$node\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (max by (device) (node_filesystem_avail_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", node_name=\"$node\"} / node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", node_name=\"$node\"}))",
     "legendFormat": "{{ device }}"
    }
   ]
  }
 ]
}
{
 "title": "Pods",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{job=\"kubernetes-nodes-cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"POD\", image!=\"\"})",
     "legendFormat": "Current Usage"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"memory\", job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits_memory_bytes{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Container Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (container_memory_usage_bytes{job=\"kubernetes-nodes-cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", container!=\"POD\"})",
     "legendFormat": "Current: {{ container }}"
    },
    {
     "expr": "sum by(container) (kube_pod_container_resource_requests{resource=\"memory\", job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"})",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "sum by(container) (kube_pod_container_resource_limits_memory_bytes{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"})",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{job=\"kubernetes-nodes-cadvisor\", image!=\"\",container!=\"POD\",pod=\"$pod\"}[1m]))",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{job=\"kubernetes-nodes-cadvisor\", namespace=\"$namespace\", pod=\"$pod\"}[1m])",
     "legendFormat": "bytes"
    }
   ]
  }
 ]
}
{
 "title": "StatefulSets",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_statefulset_metadata_generation{job=\"kube-state-metrics\"}, namespace)"
   },
   {
    "name": "statefulset",
    "label": "Name",
    "query": "label_values(kube_statefulset_metadata_generation{job=\"kube-state-metrics\", namespace=\"$namespace\"}, statefulset)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubernetes-nodes-cadvisor\", namespace=\"$namespace\", pod=~\"$statefulset.*\", container!=\"\"}[3m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{job=\"kubernetes-nodes-cadvisor\", namespace=\"$namespace\", pod=~\"$statefulset.*\", container!=\"\"}) / 1024^3"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=\"kubernetes-nodes-cadvisor\", namespace=\"$namespace\", pod=~\"$statefulset.*\", container!=\"\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$statefulset.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{job=\"kube-state-metrics\", namespace=\"$namespace\", statefulset=\"$statefulset\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Replicas of current version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(kube_statefulset_status_replicas_current{job=\"kube-state-metrics\", namespace=\"$namespace\", statefulset=\"$statefulset\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_statefulset_status_observed_generation{job=\"kube-state-metrics\",  namespace=\"$namespace\", statefulset=\"$statefulset\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_statefulset_metadata_generation{job=\"kube-state-metrics\", statefulset=\"$statefulset\", namespace=\"$namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{job=\"kube-state-metrics\", statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "replicas specified"
    },
    {
     "expr": "max(kube_statefulset_status_replicas{job=\"kube-state-metrics\", statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "replicas created"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_ready{job=\"kube-state-metrics\", statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "ready"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_current{job=\"kube-state-metrics\", statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "replicas of current version"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_updated{job=\"kube-state-metrics\", statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "updated"
    }
   ]
  }
 ]
}