{{- if .Values.ruler.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "cortex.fullname" . }}-ruler
  labels:
    app: {{ template "cortex.name" . }}
    chart: {{ template "cortex.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- if .Values.ruler.serviceMonitor.additionalLabels }}
{{ toYaml .Values.ruler.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
  {{- if .Values.ruler.serviceMonitor.annotations }}
  annotations:
{{ toYaml .Values.ruler.serviceMonitor.annotations | indent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "cortex.name" . }}-ruler
      release: {{ .Release.Name | quote }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  endpoints:
  - port: http-metrics
    {{- if .Values.ruler.serviceMonitor.interval }}
    interval: {{ .Values.ruler.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.ruler.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.ruler.serviceMonitor.scrapeTimeout }}
    {{- end }}
{{- end }}