{{- if not .Values.useExternalConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cortex.fullname" . }}
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
data:
  cortex.yaml: {{ tpl (toYaml .Values.config) . | b64enc }}
{{- end }}
