{{- if not .Values.useExternalConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cortex.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "cortex.name" . }}
    chart: {{ template "cortex.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  cortex.yaml: {{ tpl (toYaml .Values.config) . | b64enc}}
{{- end }}