{{- if and (gt (int .Values.nginx.replicas) 1) (.Values.nginx.podDisruptionBudget) }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cortex.nginxFullname" . }}
  labels:
    {{- include "cortex.nginxLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cortex.nginxSelectorLabels" . | nindent 6 }}
  {{- toYaml .Values.nginx.podDisruptionBudget | nindent 2 }}
{{- end }}
